// <auto-generated />
using System;
using MBA_DevXpert_PEO.PagamentoEFaturamento.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBA_DevXpert_PEO.PagamentoEFaturamento.Infra.Migrations
{
    [DbContext(typeof(PagamentosContext))]
    partial class PagamentosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MBA_DevXpert_PEO.PagamentoEFaturamento.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.PagamentoEFaturamento.Domain.Entities.Pagamento", b =>
                {
                    b.OwnsOne("MBA_DevXpert_PEO.PagamentoEFaturamento.Domain.ValueObjects.DadosCartao", "Cartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasColumnType("varchar(4)")
                                .HasColumnName("CVV");

                            b1.Property<string>("NomeTitular")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("NomeTitular");

                            b1.Property<string>("NumeroCartao")
                                .IsRequired()
                                .HasColumnType("varchar(19)")
                                .HasColumnName("NumeroCartao");

                            b1.Property<string>("Vencimento")
                                .IsRequired()
                                .HasColumnType("varchar(5)")
                                .HasColumnName("Vencimento");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.OwnsOne("MBA_DevXpert_PEO.PagamentoEFaturamento.Domain.ValueObjects.StatusPagamento", "Status", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Valor")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StatusPagamento");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("Cartao")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
