// <auto-generated />
using System;
using MBA_DevXpert_PEO.GestaoDeAlunos.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBA_DevXpert_PEO.GestaoDeAlunos.Infra.Migrations
{
    [DbContext(typeof(GestaoDeAlunosContext))]
    [Migration("20250430185902_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Certificados", (string)null);
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AlunoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Matricula", null)
                        .WithOne("Certificado")
                        .HasForeignKey("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Certificado", "MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Aluno", null)
                        .WithMany("Matriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.ValueObjects.HistoricoAprendizado", "Historico", b1 =>
                        {
                            b1.Property<Guid>("MatriculaId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("AulasConcluidas")
                                .HasColumnType("INTEGER")
                                .HasColumnName("AulasConcluidas");

                            b1.Property<int>("TotalAulas")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TotalAulas");

                            b1.HasKey("MatriculaId");

                            b1.ToTable("Matriculas");

                            b1.WithOwner()
                                .HasForeignKey("MatriculaId");
                        });

                    b.Navigation("Historico")
                        .IsRequired();
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("MBA_DevXpert_PEO.GestaoDeAlunos.Domain.Entities.Matricula", b =>
                {
                    b.Navigation("Certificado");
                });
#pragma warning restore 612, 618
        }
    }
}
